# Compose file for local development

version: '2'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: [yarn, dev]
    environment:
      - DATABASE_URL=postgres://tn-events:tn-events@database/tn-events
    ports:
      - "8888:80"
    volumes:
      - ./backend/src:/app/src
    links:
      - database
  
  database:
    image: postgres:9.6.3-alpine
    environment:
      - POSTGRES_DB=tn-events
      - POSTGRES_USER=tn-events
      - POSTGRES_PASSWORD=tn-events
    ports:
      - "4432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local